### ISSUE TITLE
🐞 403 Forbidden when fetching am_i_eligible_covid19vaccine_gov for NY

### ISSUE THREAD

**Issue by Graham42** [CAVaccineInventory/vaccine-feed-ingest#336] opened 2021-05-01 23:11 UTC
Fetching am_i_eligible_covid19vaccine_gov  for NY now returns
```html
<!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
```

This causes a parse error when trying to run the next stage.

To reproduce
```
poetry run vaccine-feed-ingest fetch --state
poetry run vaccine-feed-ingest parse --state
```

**Comment by skbdpup** [comment] 2021-05-02 15:40
This seems to be affecting the upstream website as well: I don't see any results when I visit https://am-i-eligible.covid19vaccine.health.ny.gov/, and I see the request to the same URL we use fail in the same way (403).

![browser screenshot](http://skbdpup.com/share/vaccine-feed-ingest-issue-336-upstream-website-broken.png)

**Comment by luhart** [comment] 2021-05-02 16:36
I'm unable to reproduce this error. It might have been something going wrong on am_i_eligible_covid19vaccine_gov's end?

**Comment by eliblock** [comment] 2021-05-05 06:00
Given that this no longer seems to occur, I'm going to close the issue.

**Closed by eliblock** 2021-05-05 06:00 UTC
Labels: priority, runner/fetch
